<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260717163709 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create user_feedback_review table with unique OneToOne FK to user_feedback';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE user_feedback_review (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, tone VARCHAR(255) NOT NULL, comment TEXT NOT NULL, feedback_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_56D3D907D249A887 ON user_feedback_review (feedback_id)');
        $this->addSql('ALTER TABLE user_feedback_review ADD CONSTRAINT FK_56D3D907D249A887 FOREIGN KEY (feedback_id) REFERENCES user_feedback (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE user_feedback_review DROP CONSTRAINT FK_56D3D907D249A887');
        $this->addSql('DROP TABLE user_feedback_review');
    }
}
